repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: end-of-file-fixer
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: trailing-whitespace
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: requirements-txt-fixer
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
      - id: mixed-line-ending
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
  # lint the dockerfiles
  - repo: https://github.com/hadolint/hadolint
    rev: c3dc18df7a501f02a560a2cc7ba3c69a85ca01d3  # frozen: v2.13.1-beta
    hooks:
      - id: hadolint
  - repo: https://github.com/codespell-project/codespell.git
    rev: "63c8f8312b7559622c0d82815639671ae42132ac"  # frozen: v2.4.1
    hooks:
      - id: codespell
        types: [text]
        exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|.+\.json|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other|rootfs/webapp/adsb.py|acarshub-typescript/src/interfaces.ts)
